# Generated by Django 3.1.1 on 2020-09-27 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('naming_scheme', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('datasheet', models.FileField(blank=True, upload_to='')),
                ('pinout', models.ImageField(blank=True, upload_to='')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.container')),
                ('tags', models.ManyToManyField(blank=True, to='parts.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
