# Generated by Django 3.1.1 on 2020-09-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20200928_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
