# Generated by Django 3.1.1 on 2020-10-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200928_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
    ]
